"""
Django settings for LearnLM project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""
import os
from pathlib import Path
from dotenv import load_dotenv # <--- ADDED THIS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 👇 ADDED THIS: Force dotenv to look exactly where manage.py lives BEFORE any keys are requested
env_path = os.path.join(BASE_DIR, '.env')
load_dotenv(dotenv_path=env_path)


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "fallback-secret-key-for-local-dev")

def _guard_production_secret_key():
    # Refuse to start a production instance on the well-known dev key —
    # a leaked SECRET_KEY invalidates sessions, password reset tokens and
    # JWT signing (SIMPLE_JWT signs with it).
    from django.core.exceptions import ImproperlyConfigured
    if SECRET_KEY == "fallback-secret-key-for-local-dev":
        raise ImproperlyConfigured(
            "Set a real SECRET_KEY in the environment before running with DJANGO_DEBUG=false."
        )

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults keep local development working; production flips these in .env:
#   DJANGO_DEBUG=false
#   DJANGO_ALLOWED_HOSTS=sparklm.example.com,api.sparklm.example.com
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",") if h.strip()]

if not DEBUG:
    # Sensible HTTPS-deployment defaults (behind a TLS-terminating proxy).
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    _guard_production_secret_key()

# Application definition
INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "groups.apps.GroupsConfig",
    "common.apps.CommonConfig",
    "rest_framework",
    "rest_framework_simplejwt",
    # Refresh-token replay detection (M5 Phase 4). Rotation without a record
    # of spent tokens is theatre — the old token stays valid for its full
    # remaining lifetime. Adds OutstandingToken/BlacklistedToken plus one
    # write per rotation. See CookieTokenRefreshMixin for why rotation is
    # bound to the AUTH_V2_COOKIES flag and not to a global setting.
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "channels",
    "pgvector",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise serves collected static files (admin CSS/JS) directly
    # from Daphne — there is no separate web server in the Render topology.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # One access-log line per API request (M8) — Daphne has no access log.
    "common.logging_middleware.AccessLogMiddleware",
    # Bounded in-flight admission control (M4 Phase A). Placed BELOW the
    # access log so rejections are still logged, and ABOVE session/auth so a
    # shed request does not pay for a session lookup or a JWT verify it is
    # not going to use. Overload becomes a fast 503 instead of a 502 issued
    # after 20+ seconds of work has already been spent.
    "common.middleware.AdmissionControlMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "LearnLM.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "LearnLM.wsgi.application"
ASGI_APPLICATION = 'LearnLM.asgi.application'


# Database — credentials come from .env in production; defaults match the
# existing local setup so development keeps working unchanged.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'learnlm_db'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'yourpassword'),
        'HOST': os.getenv('POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),

        # ── R1: process-wide connection pool ─────────────────────────────
        #
        # This slot used to hold CONN_MAX_AGE=60, with a comment claiming it
        # "lets each worker thread reuse one connection across requests".
        # That was wrong, and measurably so.
        #
        # Django's ASGIHandler wraps every request in `async with
        # ThreadSensitiveContext()`, which mints a fresh executor thread per
        # request. django.db.connections is thread-critical
        # (asgiref Local(thread_critical=True)), so each new thread starts
        # with NO connection and dials Neon again. CONN_MAX_AGE can only
        # persist a connection WITHIN one thread, so under Daphne it never
        # applied at all.
        #
        # Measured against real Daphne (not the test client, which reuses a
        # single thread and hides this): 12 requests produced 12 connections
        # on 12 distinct thread ids. Counting TCP sockets to Neon:5432,
        # 20 requests opened 21 sockets — one per request.
        #
        # OPTIONS['pool'] fixes it because psycopg_pool lives in
        # DatabaseWrapper._connection_pools, a CLASS attribute shared by
        # every per-thread wrapper. The pool outlives the request threads.
        # Same measurement after: 20 requests reused 3 sockets.
        #
        # Pooling and persistent connections are mutually exclusive —
        # CONN_MAX_AGE must be 0 or Django raises ImproperlyConfigured
        # (django/db/backends/postgresql/base.py).
        'CONN_MAX_AGE': 0,

        # NOT optional. Neon's pooler drops idle connections and the free
        # tier auto-suspends its compute, so a pooled connection can be dead
        # by the time it is handed out. Observed twice with this disabled:
        #   WARNING pool discarding closed connection: <Connection [BAD]>
        #   ERROR   Service Unavailable: /healthz
        # The pool only discards the corpse AFTER the request has failed.
        # Django wires this setting to psycopg_pool's checkout validation
        # (postgresql/base.py: check=ConnectionPool.check_connection).
        # Costs exactly one round-trip per checkout; the handshake it
        # replaces costs about 7.2.
        'CONN_HEALTH_CHECKS': True,

        'OPTIONS': {
            'pool': {
                # One Daphne process. Queries are short (~33 ms measured),
                # so a small pool serves far more throughput than this
                # instance can generate; sized for burst arrival, not
                # sustained load.
                'min_size': 2,
                'max_size': 10,
                # Seconds a request may wait for a free connection before
                # raising PoolTimeout rather than hanging.
                'timeout': 10,
                # Recycle before anything upstream can: Neon free-tier
                # compute auto-suspends after ~5 minutes idle. Both are
                # handled by the pool's background worker, off the request
                # path.
                'max_idle': 300,
                'max_lifetime': 1800,
            },
        },
    }
}

# Cache — the DAG graph cache (hybrid_router) and DRF throttles live here.
# With the default per-process LocMemCache, cache invalidation only reaches
# the worker that made the change; set REDIS_URL in production so all
# Gunicorn/Daphne workers share one cache.
REDIS_URL = os.getenv("REDIS_URL")
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

import sys
if 'pytest' in sys.modules or 'pytest' in sys.argv[0]:
    pass


# Password hashing (M3). Order is preference order: the FIRST entry hashes
# new and upgraded passwords, and every entry can verify.
#
# PBKDF2 stays listed second on purpose — it is what the existing user base
# is stored under, and Django rehashes each account to Argon2 transparently
# on its next successful login (AbstractBaseUser.check_password supplies a
# setter that persists the upgrade). Removing it would lock those users out.
#
# ⚠ ROLLBACK IS A REORDER, NEVER A REMOVAL. Once a user has logged in after
# this deploy, their stored hash IS Argon2. Dropping TunedArgon2PasswordHasher
# from this list — or uninstalling argon2-cffi — makes identify_hasher() raise,
# which Django reports as an ordinary failed login. Every migrated user would
# be locked out, silently. To roll back, move PBKDF2 to the front and leave
# Argon2 in place. See docs/DEPLOYMENT.md.
# Entries are limited to algorithms actually present in the database. A
# PBKDF2SHA1 entry was carried here briefly as "costless insurance"; an audit
# of production found zero SHA1 hashes, so it insured nothing while keeping a
# weaker algorithm in the verification path. Add an entry only when a stored
# hash needs it.
PASSWORD_HASHERS = [
    "common.hashers.TunedArgon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]


# Password validation. NOTE: this list only takes effect where something
# actually calls django.contrib.auth.password_validation.validate_password()
# — DRF's ModelSerializer does NOT wire it in automatically. That call
# lives in UserSerializer.validate_password (groups/serializers.py); prior
# to that method existing, every validator below was configured but never
# invoked, so registration silently accepted any password.
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 8},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "groups.validators.PasswordComplexityValidator",
    },
]


# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
# Required for `collectstatic` on deploy (admin CSS/JS etc.).
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# Hashed + compressed static files served by WhiteNoise behind Daphne.
# Manifest storage only outside DEBUG: it requires a collectstatic run,
# which development and the test suite don't perform.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
}
if not DEBUG:
    STORAGES["staticfiles"] = {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
    }

# ── Durable object storage (M5 Phase 3) ──────────────────────────────────
#
# Render's filesystem is ephemeral: every deploy discards uploaded files, so
# download, preview and the vision path have been breaking on each restart
# and four pre-Phase-C materials have lost their files permanently.
#
# Provider-agnostic on purpose. django-storages speaks the S3 API, so
# Cloudflare R2, Backblaze B2, AWS S3 and MinIO differ only in
# AWS_S3_ENDPOINT_URL. Nothing here names a vendor.
#
# Unconfigured => FileSystemStorage, so development and CI need no
# credentials and no network. Setting AWS_STORAGE_BUCKET_NAME is the single
# switch that turns this on.
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "")
AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL") or None
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "auto")
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "")

# Lifetime of a signed download URL. Short deliberately: a URL that outlives
# the session is the unauthenticated /media/ problem again with extra steps.
SIGNED_URL_TTL = int(os.getenv("SIGNED_URL_TTL", "300"))

# Defined unconditionally so the security-critical options are always
# assertable. Guarding them only inside `if AWS_STORAGE_BUCKET_NAME` meant
# the test that checks them SKIPPED in every environment that does not have
# a bucket — i.e. CI and development, which is everywhere the check would
# actually run. Mutation testing caught that: flipping default_acl to
# public-read was not detected by anything.
S3_STORAGE_OPTIONS = {
    # PRIVATE BUCKET. `default_acl=None` leaves objects governed by the
    # bucket policy rather than stamping them public-read, and
    # querystring_auth=True means .url is a signed URL, never a bare public
    # one. Both are load-bearing: the M4 audit proved a leaked /media/ link
    # was a permanent, unrevocable handle to the bytes.
    "default_acl": None,
    "querystring_auth": True,
    "querystring_expire": SIGNED_URL_TTL,
    # Never overwrite: two materials named notes.pdf must not collide, and
    # an overwrite would silently destroy the first user's file.
    "file_overwrite": False,
    # R2 and most S3-compatibles require virtual-hosted addressing.
    "addressing_style": "virtual",
    "signature_version": "s3v4",
}

if AWS_STORAGE_BUCKET_NAME:
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": dict(S3_STORAGE_OPTIONS),
    }
# In DEBUG, serve straight from the app's static dirs per request instead
# of pre-scanning a STATIC_ROOT that may not have been collected yet.
WHITENOISE_AUTOREFRESH = DEBUG

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Local dev origins by default; production supplies its SPA origin(s) via
# env, e.g. CORS_ALLOWED_ORIGINS=https://sparklm.vercel.app
_default_cors = "http://localhost:3000,http://localhost:5173,http://localhost:8080,http://172.19.0.1:8080"
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.getenv("CORS_ALLOWED_ORIGINS", _default_cors).split(",") if o.strip()
]

# Django 4+ validates the Origin header on POSTs to the admin: the API
# host itself must be trusted when admin is used over HTTPS on Render,
# e.g. CSRF_TRUSTED_ORIGINS=https://sparklm-api.onrender.com
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]

# Allow-all only in development; production uses the explicit whitelist above.
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOW_CREDENTIALS = True


# REST_FRAMEWORK is the master config for your API
REST_FRAMEWORK = {
    # SimpleJWT's authenticator plus a token_version check (M4 Phase A).
    # The check is free: JWTAuthentication.get_user() already SELECTs the
    # user row on every authenticated request, so revocation costs one
    # integer comparison against data already in memory. See
    # common/tokens.py for why the claim rides on the refresh token.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'common.authentication.VersionedJWTAuthentication',
    ),
    # ── Default deny (M4 security sprint, WP0) ───────────────────────────
    #
    # This key was ABSENT, which does not mean "no opinion" — DRF's built-in
    # default is AllowAny, so every view was public unless someone
    # remembered to write permission_classes. One already had slipped
    # through: /api/upload-pdf/ accepted unauthenticated PDF parsing on a
    # 512 MB instance.
    #
    # The audit's other seven findings were missed manual checks; this is
    # why manual checks were the only defence. Public endpoints now opt in
    # explicitly with permission_classes = [AllowAny], which is greppable,
    # reviewable, and enforced by common/test_authorization_matrix.py.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 3,
    # Client-IP-aware variants: Render's LAST X-Forwarded-For hop is a
    # rotating internal load balancer, which silently defeated every
    # throttle. See common/throttling.py for the measurement and the
    # spoofability trade-off this accepts.
    'DEFAULT_THROTTLE_CLASSES': [
        'common.throttling.ClientIPAnonRateThrottle',
        'common.throttling.ClientIPUserRateThrottle'
    ],
    # Trust exactly N reverse proxies when identifying anonymous clients.
    # Left unset, DRF trusts the raw client-supplied X-Forwarded-For header,
    # so an attacker behind our proxy could rotate spoofed IPs and bypass
    # every IP-keyed throttle (including the auth brute-force brake). With
    # N=1, only the proxy-appended (unspoofable) last hop identifies the
    # client. Set DRF_NUM_PROXIES to match the deployment's proxy depth.
    'NUM_PROXIES': int(os.getenv('DRF_NUM_PROXIES', '1')),
    # ── Rate limits are a CAPACITY control here, not only a security one ──
    #
    # Phase B measured the free-tier instance to destruction. Django's ASGI
    # handler runs every sync view on ONE thread-sensitive worker (proven:
    # peak overlap 1 at 32-way concurrency), so requests do not run in
    # parallel — they queue. Serialised cost of a login is ~0.63 s, so the
    # instance sustains ~1.6 logins/s and no more, whatever the arrival rate.
    #
    # Measured behaviour of a single client IP:
    #     10 concurrent  ->   7.1 s, 0 failures          healthy
    #     20 concurrent  -> 103.0 s, 0 failures          degraded
    #     40 concurrent  ->  32/40 -> 502, ~60 s outage  BROKEN
    #
    # The previous ceiling let one IP send anon(30) + auth(10) = 40/min —
    # precisely the load that took production down. A caller could exhaust
    # the service without ever exceeding its rate limit. The ceiling is now
    # 20/min, the highest level measured to complete without failures.
    #
    # ⚠ These are per-IP. A campus behind one NAT shares a bucket, so this
    # trades some legitimate-user headroom for survivability. Raise them only
    # together with real capacity (paid instance, or admission control) —
    # never on their own. See docs/DEPLOYMENT.md.
    'DEFAULT_THROTTLE_RATES': {
        # Global defaults. The SPA fires several API calls per page load
        # (dashboard, portals, profile, notifications), so 20/min per user
        # 429s legitimate browsing — 120/min ≈ 2 req/s sustained.
        #
        # 'anon' lowered 30 -> 15: anonymous callers only reach login,
        # register and Google auth, so 15/min is ample for a human while
        # halving the burst one IP can aim at the auth pipeline.
        'anon': '15/minute',
        'user': '120/minute',
        # Scoped rates for expensive endpoints (see throttle_scope on views):
        # each code run/submit fans out to N Judge0 calls (paid API), and
        # /code/next/ can trigger an LLM test-case generation.
        'judge0': '10/minute',
        'recommend': '30/minute',
        # Token endpoints, keyed by IP for anonymous callers. Separate
        # buckets: 'auth' (login) is the credential-stuffing brake; refresh
        # presents an existing token (not guessable credentials) and gets a
        # looser bucket so refresh traffic behind a shared NAT can never
        # starve logins (frozen architecture §7).
        #
        # 'auth' lowered 10 -> 5: login is the most expensive anonymous
        # operation (~0.63 s serialised, of which ~127 ms is Argon2), and
        # 5 attempts/min is still well above human behaviour.
        'auth': '5/minute',
        'auth-refresh': '30/minute',
        # Joining by code is a guessing surface: one correct code grants
        # full membership (materials, chat, quizzes). Codes are now
        # server-generated from a 31-character alphabet at length 10, so
        # brute force is already infeasible — this bounds the attempt rate
        # as well, since defence in depth on a credential-shaped secret
        # costs one line. 10/min is far above any human joining flow.
        'group-join': '10/minute',
    }
}

from datetime import timedelta

# ── Admission control (M4 Phase A) ───────────────────────────────────────
#
# Maximum requests in flight before shedding with 503 + Retry-After.
#
# 12 is derived, not chosen. Milestone 3 measured this instance serialising
# sync views onto one worker, so the n-th queued request waits roughly n × W:
#
#     10 concurrent ->   7.1 s, 0 failures        healthy
#     20 concurrent -> 103.0 s, 0 failures        degraded but "passing"
#     40 concurrent ->  32/40 -> 502, ~60 s outage
#
# 20 is where it BREAKS, not where it is usable — 103-second responses are a
# failure with a 200 status. Sizing from acceptable wait instead:
# W ≈ 0.6 s server-side for a login, a 10 s tolerance gives ~16, rounded down
# to 12 for margin. Raise this only with a measurement, not a hunch.
#
# 0 disables the middleware entirely (logged loudly at boot).
ADMISSION_LIMIT = int(os.getenv("ADMISSION_LIMIT", "12"))

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    # Separate signing key from SECRET_KEY (M4 Phase A).
    #
    # Sharing them couples three failure domains: SECRET_KEY signs session
    # cookies and password-reset tokens as well, so rotating it to invalidate
    # JWTs also invalidates every reset link and logs out every admin
    # session. With a distinct key, JWT signing can be rotated on its own.
    #
    # Falls back to SECRET_KEY when JWT_SIGNING_KEY is unset, so this change
    # is non-breaking: nothing is invalidated until the variable is
    # deliberately set. ⚠ Setting or changing it IS a fleet-wide logout —
    # every outstanding token fails signature verification. That is the
    # intended behaviour of a key rotation, but do it knowingly.
    'SIGNING_KEY': os.getenv("JWT_SIGNING_KEY") or SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    # ⚠ ROTATE_REFRESH_TOKENS / BLACKLIST_AFTER_ROTATION are deliberately
    # NOT set here (M5 Phase 4). Setting them globally would rotate on the
    # legacy path too, and the currently-deployed frontend stores the new
    # `access` on refresh but never updates its stored refresh token — so
    # every old client would break permanently after its first refresh.
    # Rotation is implemented in CookieTokenRefreshMixin and bound to the
    # AUTH_V2_COOKIES flag, so flag-off behaviour is byte-identical to
    # today's. See common/auth_views.py.
}

# ── Auth v2: httpOnly refresh cookies (M5 Phase 4) ───────────────────────
#
# OFF by default. With the flag off not a single response header changes —
# the legacy localStorage flow is untouched, which is what makes this
# deployable ahead of the frontend and reversible without a code change.
#
# Rollout: deploy the new frontend (it works under both settings), THEN set
# AUTH_V2_COOKIES=true. Rollback: unset it. Neither direction logs anyone
# out, because read_refresh_token() accepts the cookie OR the request body.
AUTH_V2_COOKIES = os.getenv("AUTH_V2_COOKIES", "false").lower() == "true"

# Cookie attributes. The defaults are the production-correct values; they
# are overridable only so the test client and local HTTP development work.
#
# SameSite=None is a requirement, not a weakening: the SPA (Vercel) and the
# API (Render) are different sites, so Lax would never send the cookie at
# all. That is exactly why the refresh and logout endpoints require a
# custom header — see CSRF_SENTINEL_HEADER in common/auth_cookies.py.
AUTH_COOKIE_SECURE = os.getenv("AUTH_COOKIE_SECURE", str(not DEBUG)).lower() == "true"
AUTH_COOKIE_SAMESITE = os.getenv("AUTH_COOKIE_SAMESITE", "None")
AUTH_COOKIE_PATH = os.getenv("AUTH_COOKIE_PATH", "/api/")

AUTH_USER_MODEL = 'groups.User'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 👇 Because load_dotenv() is at the top, these will now successfully grab your keys!
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
# Backup provider: NVIDIA NIM is called only when Groq's DAILY token quota
# is exhausted (ai_services._generate_json_with_fallback). Optional — if
# unset, Groq's daily cap still stops the run cleanly exactly as before.
NIM_API_KEY = os.getenv("NIM_API_KEY")
# Google Sign-In: the OAuth Client ID is the audience GoogleAuthView checks
# ID tokens against — NOT a secret (it's also shipped to the browser as
# VITE_GOOGLE_CLIENT_ID), but it must match exactly or every token is
# rejected.
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
JUDGE0_API_KEY = os.getenv("JUDGE0_API_KEY")
JUDGE0_API_HOST = os.getenv("JUDGE0_API_HOST", "judge0-extra-ce.p.rapidapi.com")

# Channel layer for Daphne/Channels WebSockets.
# In-memory works for a SINGLE Daphne process only — with multiple
# instances, group messages don't cross processes. When REDIS_URL is set
# and channels-redis is installed, use Redis so chat works fleet-wide.
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}
if REDIS_URL:
    try:
        import channels_redis  # noqa: F401
        CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels_redis.core.RedisChannelLayer",
                "CONFIG": {"hosts": [REDIS_URL]},
            }
        }
    except ImportError:
        pass  # keep in-memory; install channels-redis for multi-instance

# --- EMAIL SETTINGS (Day 4 Integration) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "dummy@example.com")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

# M7 staged rollout: when true, NextProblemView rejects explicitly
# requested topics whose prerequisites are unmastered (server-side
# curriculum gate). Off by default until after the demo window — the
# frontend guard already prevents starting locked topics.
CURRICULUM_GATE_ENFORCE = os.getenv("CURRICULUM_GATE_ENFORCE", "false").lower() == "true"

# --- SENTRY (M8 observability) ---
# No-op unless SENTRY_DSN is provided (set it in the Render dashboard).
SENTRY_DSN = os.getenv("SENTRY_DSN")
if SENTRY_DSN:
    import sentry_sdk
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=os.getenv("SENTRY_ENV", "development" if DEBUG else "production"),
        traces_sample_rate=float(os.getenv("SENTRY_TRACES_RATE", "0.1")),
        send_default_pii=False,
    )

# --- OBSERVABILITY LOGGING ---
import logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'groups': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'access': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        }
    }
}