"""
Django settings for LearnLM project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""
import os
from pathlib import Path
from dotenv import load_dotenv # <--- ADDED THIS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 👇 ADDED THIS: Force dotenv to look exactly where manage.py lives BEFORE any keys are requested
env_path = os.path.join(BASE_DIR, '.env')
load_dotenv(dotenv_path=env_path)


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "fallback-secret-key-for-local-dev")

def _guard_production_secret_key():
    # Refuse to start a production instance on the well-known dev key —
    # a leaked SECRET_KEY invalidates sessions, password reset tokens and
    # JWT signing (SIMPLE_JWT signs with it).
    from django.core.exceptions import ImproperlyConfigured
    if SECRET_KEY == "fallback-secret-key-for-local-dev":
        raise ImproperlyConfigured(
            "Set a real SECRET_KEY in the environment before running with DJANGO_DEBUG=false."
        )

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults keep local development working; production flips these in .env:
#   DJANGO_DEBUG=false
#   DJANGO_ALLOWED_HOSTS=sparklm.example.com,api.sparklm.example.com
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",") if h.strip()]

if not DEBUG:
    # Sensible HTTPS-deployment defaults (behind a TLS-terminating proxy).
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    _guard_production_secret_key()

# Application definition
INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "groups.apps.GroupsConfig",
    "common.apps.CommonConfig",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "channels",
    "pgvector",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise serves collected static files (admin CSS/JS) directly
    # from Daphne — there is no separate web server in the Render topology.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # One access-log line per API request (M8) — Daphne has no access log.
    "common.logging_middleware.AccessLogMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "LearnLM.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "LearnLM.wsgi.application"
ASGI_APPLICATION = 'LearnLM.asgi.application'


# Database — credentials come from .env in production; defaults match the
# existing local setup so development keeps working unchanged.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'learnlm_db'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'yourpassword'),
        'HOST': os.getenv('POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}

# Cache — the DAG graph cache (hybrid_router) and DRF throttles live here.
# With the default per-process LocMemCache, cache invalidation only reaches
# the worker that made the change; set REDIS_URL in production so all
# Gunicorn/Daphne workers share one cache.
REDIS_URL = os.getenv("REDIS_URL")
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

import sys
if 'pytest' in sys.modules or 'pytest' in sys.argv[0]:
    pass


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
# Required for `collectstatic` on deploy (admin CSS/JS etc.).
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# Hashed + compressed static files served by WhiteNoise behind Daphne.
# Manifest storage only outside DEBUG: it requires a collectstatic run,
# which development and the test suite don't perform.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
}
if not DEBUG:
    STORAGES["staticfiles"] = {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
    }
# In DEBUG, serve straight from the app's static dirs per request instead
# of pre-scanning a STATIC_ROOT that may not have been collected yet.
WHITENOISE_AUTOREFRESH = DEBUG

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Local dev origins by default; production supplies its SPA origin(s) via
# env, e.g. CORS_ALLOWED_ORIGINS=https://sparklm.vercel.app
_default_cors = "http://localhost:3000,http://localhost:5173,http://localhost:8080,http://172.19.0.1:8080"
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.getenv("CORS_ALLOWED_ORIGINS", _default_cors).split(",") if o.strip()
]

# Django 4+ validates the Origin header on POSTs to the admin: the API
# host itself must be trusted when admin is used over HTTPS on Render,
# e.g. CSRF_TRUSTED_ORIGINS=https://sparklm-api.onrender.com
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]

# Allow-all only in development; production uses the explicit whitelist above.
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOW_CREDENTIALS = True


# REST_FRAMEWORK is the master config for your API
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 3,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    # Trust exactly N reverse proxies when identifying anonymous clients.
    # Left unset, DRF trusts the raw client-supplied X-Forwarded-For header,
    # so an attacker behind our proxy could rotate spoofed IPs and bypass
    # every IP-keyed throttle (including the auth brute-force brake). With
    # N=1, only the proxy-appended (unspoofable) last hop identifies the
    # client. Set DRF_NUM_PROXIES to match the deployment's proxy depth.
    'NUM_PROXIES': int(os.getenv('DRF_NUM_PROXIES', '1')),
    'DEFAULT_THROTTLE_RATES': {
        # Global defaults. The SPA fires several API calls per page load
        # (dashboard, portals, profile, notifications), so 20/min per user
        # 429s legitimate browsing — 120/min ≈ 2 req/s sustained.
        'anon': '30/minute',
        'user': '120/minute',
        # Scoped rates for expensive endpoints (see throttle_scope on views):
        # each code run/submit fans out to N Judge0 calls (paid API), and
        # /code/next/ can trigger an LLM test-case generation.
        'judge0': '10/minute',
        'recommend': '30/minute',
        # Token endpoints, keyed by IP for anonymous callers. Separate
        # buckets: 'auth' (login) is the credential-stuffing brake; refresh
        # presents an existing token (not guessable credentials) and gets a
        # looser bucket so refresh traffic behind a shared NAT can never
        # starve logins (frozen architecture §7).
        'auth': '10/minute',
        'auth-refresh': '30/minute',
    }
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

AUTH_USER_MODEL = 'groups.User'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 👇 Because load_dotenv() is at the top, these will now successfully grab your keys!
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
JUDGE0_API_KEY = os.getenv("JUDGE0_API_KEY")
JUDGE0_API_HOST = os.getenv("JUDGE0_API_HOST", "judge0-extra-ce.p.rapidapi.com")

# Channel layer for Daphne/Channels WebSockets.
# In-memory works for a SINGLE Daphne process only — with multiple
# instances, group messages don't cross processes. When REDIS_URL is set
# and channels-redis is installed, use Redis so chat works fleet-wide.
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}
if REDIS_URL:
    try:
        import channels_redis  # noqa: F401
        CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels_redis.core.RedisChannelLayer",
                "CONFIG": {"hosts": [REDIS_URL]},
            }
        }
    except ImportError:
        pass  # keep in-memory; install channels-redis for multi-instance

# --- EMAIL SETTINGS (Day 4 Integration) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "dummy@example.com")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

# M7 staged rollout: when true, NextProblemView rejects explicitly
# requested topics whose prerequisites are unmastered (server-side
# curriculum gate). Off by default until after the demo window — the
# frontend guard already prevents starting locked topics.
CURRICULUM_GATE_ENFORCE = os.getenv("CURRICULUM_GATE_ENFORCE", "false").lower() == "true"

# --- SENTRY (M8 observability) ---
# No-op unless SENTRY_DSN is provided (set it in the Render dashboard).
SENTRY_DSN = os.getenv("SENTRY_DSN")
if SENTRY_DSN:
    import sentry_sdk
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=os.getenv("SENTRY_ENV", "development" if DEBUG else "production"),
        traces_sample_rate=float(os.getenv("SENTRY_TRACES_RATE", "0.1")),
        send_default_pii=False,
    )

# --- OBSERVABILITY LOGGING ---
import logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'groups': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'access': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        }
    }
}