# Generated by Django 5.2.8 on 2026-07-04 10:18

import django.db.models.deletion
import groups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0028_alter_document_feature_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenticcoachlog',
            name='problem_id',
        ),
        migrations.RemoveField(
            model_name='codesubmission',
            name='problem_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AlterUniqueTogether(
            name='usertopicmastery',
            unique_together={('user', 'topic')},
        ),
        migrations.AddField(
            model_name='agenticcoachlog',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_logs_on_question', to='groups.question'),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='groups.question'),
        ),
        migrations.AlterField(
            model_name='assignedquiz',
            name='deadline',
            field=models.DateTimeField(default=groups.models.default_deadline),
        ),
        migrations.AlterField(
            model_name='recommendationlog',
            name='recommended_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.topic'),
        ),
        migrations.AlterField(
            model_name='usertopicmastery',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.topic'),
        ),
        migrations.CreateModel(
            name='TopicPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='groups.topic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='groups.topic')),
            ],
            options={
                'unique_together': {('topic', 'prerequisite')},
            },
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
        migrations.RemoveField(
            model_name='usertopicmastery',
            name='subject',
        ),
    ]
