# Generated by Django 5.2.8 on 2026-07-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0029_remove_agenticcoachlog_problem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenticcoachlog',
            name='hint_source',
            field=models.CharField(default='fallback', max_length=20),
        ),
        migrations.AddField(
            model_name='agenticcoachlog',
            name='webhook_latency_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertopicmastery',
            name='last_decay_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
