# Generated by Django 5.2.16 on 2026-08-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0033_add_token_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationlog',
            name='policy_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
