# Generated by Django 5.2.16 on 2026-08-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0034_add_policy_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
