# Generated by Django 5.2.16 on 2026-08-10 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0035_cache_extracted_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('source_code', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_solutions', to='groups.question')),
            ],
            options={
                'indexes': [models.Index(fields=['question', 'is_active'], name='refsol_question_active_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('question', 'language'), name='one_active_reference_solution_per_language')],
            },
        ),
    ]
