# Generated by Django 5.2.16 on 2026-08-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0036_referencesolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='execution_contract_version',
            field=models.CharField(default='v1', max_length=8),
        ),
    ]
