# Generated by Django 5.2.16 on 2026-08-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0037_question_execution_contract_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='adaptive_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending review'), ('PUBLISHED', 'Published'), ('BLOCKED', 'Blocked')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='trust_state',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('ORACLE_VERIFIED', 'Oracle verified')], default='UNVERIFIED', max_length=20),
        ),
    ]
