# Generated by Django 5.2.16 on 2026-08-12 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0039_reference_solution_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerTopicSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=1200.0)),
                ('rating_deviation', models.FloatField(default=350.0)),
                ('volatility', models.FloatField(default=0.06)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('last_evidence_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_skills', to='groups.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'topic'], name='shadow_skill_user_topic_idx')],
                'unique_together': {('user', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='QuestionSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=1200.0)),
                ('rating_deviation', models.FloatField(default=350.0)),
                ('volatility', models.FloatField(default=0.06)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('last_evidence_at', models.DateTimeField(blank=True, null=True)),
                ('prior_rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_skill', to='groups.question')),
            ],
            options={
                'indexes': [models.Index(fields=['rating'], name='shadow_qskill_rating_idx')],
            },
        ),
    ]
