# Generated by Django 5.2.16 on 2026-08-16 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0043_glicko_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_key', models.CharField(max_length=64, unique=True)),
                ('purpose', models.TextField()),
                ('state', models.CharField(choices=[('OPEN', 'Open - capturing'), ('CAPTURED', 'Captured - membership frozen'), ('APPLIED', 'Applied'), ('ROLLED_BACK', 'Rolled back')], default='OPEN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remediation_batches', to=settings.AUTH_USER_MODEL)),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remediation_batches_frozen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('trust_state', models.CharField(max_length=20)),
                ('execution_contract_version', models.CharField(max_length=8)),
                ('boilerplate_code', models.JSONField(default=dict)),
                ('hidden_wrapper_code', models.JSONField(default=dict)),
                ('hidden_test_cases', models.JSONField(default=list)),
                ('case_identities', models.JSONField(default=list)),
                ('was_adaptive_eligible', models.BooleanField(default=False)),
                ('state_digest', models.CharField(max_length=64)),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pre_images_captured', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pre_images', to='groups.question')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pre_images', to='groups.remediationbatch')),
            ],
        ),
        migrations.CreateModel(
            name='RemediationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_class', models.CharField(choices=[('CONTRACT_REPAIR', 'CONTRACT_REPAIR'), ('STATEMENT_REPAIR', 'STATEMENT_REPAIR'), ('BOILERPLATE_REPAIR', 'BOILERPLATE_REPAIR'), ('HIDDEN_TEST_REPAIR', 'HIDDEN_TEST_REPAIR'), ('EXPECTED_OUTPUT_REPAIR', 'EXPECTED_OUTPUT_REPAIR'), ('MANUAL_REVIEW', 'MANUAL_REVIEW'), ('COMPLETE_REBUILD', 'COMPLETE_REBUILD'), ('ROLLBACK', 'ROLLBACK')], max_length=32)),
                ('detail', models.TextField(blank=True, default='')),
                ('post_digest', models.CharField(max_length=64)),
                ('applied_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remediation_actions', to=settings.AUTH_USER_MODEL)),
                ('pre_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='groups.questionpreimage')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remediation_actions', to='groups.question')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='groups.remediationbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'question'], name='action_batch_question_idx'), models.Index(fields=['question', '-applied_at'], name='action_question_ts_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='questionpreimage',
            index=models.Index(fields=['question', '-captured_at'], name='pre_image_question_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='questionpreimage',
            index=models.Index(fields=['state_digest'], name='pre_image_digest_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionpreimage',
            constraint=models.UniqueConstraint(fields=('batch', 'question'), name='pre_image_one_per_question_per_batch'),
        ),
    ]
