# Generated by Django 5.2.16 on 2026-08-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0046_suite_expansion_action_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationaction',
            name='action_class',
            field=models.CharField(choices=[('CONTRACT_REPAIR', 'CONTRACT_REPAIR'), ('STATEMENT_REPAIR', 'STATEMENT_REPAIR'), ('BOILERPLATE_REPAIR', 'BOILERPLATE_REPAIR'), ('HIDDEN_TEST_REPAIR', 'HIDDEN_TEST_REPAIR'), ('EXPECTED_OUTPUT_REPAIR', 'EXPECTED_OUTPUT_REPAIR'), ('INPUT_REPAIR', 'INPUT_REPAIR'), ('SUITE_EXPANSION', 'SUITE_EXPANSION'), ('STATUS_TRANSITION', 'STATUS_TRANSITION'), ('MANUAL_REVIEW', 'MANUAL_REVIEW'), ('COMPLETE_REBUILD', 'COMPLETE_REBUILD'), ('ROLLBACK', 'ROLLBACK')], max_length=32),
        ),
    ]
