# Generated by Django 5.2.16 on 2026-08-23 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0047_status_transition_action_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationaction',
            name='action_class',
            field=models.CharField(choices=[('CONTRACT_REPAIR', 'CONTRACT_REPAIR'), ('STATEMENT_REPAIR', 'STATEMENT_REPAIR'), ('BOILERPLATE_REPAIR', 'BOILERPLATE_REPAIR'), ('HIDDEN_TEST_REPAIR', 'HIDDEN_TEST_REPAIR'), ('EXPECTED_OUTPUT_REPAIR', 'EXPECTED_OUTPUT_REPAIR'), ('INPUT_REPAIR', 'INPUT_REPAIR'), ('SUITE_EXPANSION', 'SUITE_EXPANSION'), ('STATEMENT_GENERATION', 'STATEMENT_GENERATION'), ('SIGNATURE_DECLARATION', 'SIGNATURE_DECLARATION'), ('STATUS_TRANSITION', 'STATUS_TRANSITION'), ('MANUAL_REVIEW', 'MANUAL_REVIEW'), ('COMPLETE_REBUILD', 'COMPLETE_REBUILD'), ('ROLLBACK', 'ROLLBACK')], max_length=32),
        ),
        migrations.CreateModel(
            name='ReseedLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('PENDING', 'PENDING'), ('STATEMENT_WRITTEN', 'STATEMENT_WRITTEN'), ('SIGNATURE_WRITTEN', 'SIGNATURE_WRITTEN'), ('COMPLETE', 'COMPLETE'), ('FAILED', 'FAILED')], default='PENDING', max_length=24)),
                ('last_error', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reseed_ledger', to='groups.remediationbatch')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reseed_ledger', to='groups.question')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'stage'], name='reseed_ledger_batch_stage_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'question'), name='reseed_ledger_one_per_question_per_batch')],
            },
        ),
    ]
