# Generated by Django 5.2.16 on 2026-08-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0048_reseed_action_classes_and_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationaction',
            name='action_class',
            field=models.CharField(choices=[('CONTRACT_REPAIR', 'CONTRACT_REPAIR'), ('STATEMENT_REPAIR', 'STATEMENT_REPAIR'), ('BOILERPLATE_REPAIR', 'BOILERPLATE_REPAIR'), ('HIDDEN_TEST_REPAIR', 'HIDDEN_TEST_REPAIR'), ('EXPECTED_OUTPUT_REPAIR', 'EXPECTED_OUTPUT_REPAIR'), ('INPUT_REPAIR', 'INPUT_REPAIR'), ('SUITE_EXPANSION', 'SUITE_EXPANSION'), ('STATEMENT_GENERATION', 'STATEMENT_GENERATION'), ('SIGNATURE_DECLARATION', 'SIGNATURE_DECLARATION'), ('CONTRACT_DECLARATION', 'CONTRACT_DECLARATION'), ('STATUS_TRANSITION', 'STATUS_TRANSITION'), ('MANUAL_REVIEW', 'MANUAL_REVIEW'), ('COMPLETE_REBUILD', 'COMPLETE_REBUILD'), ('ROLLBACK', 'ROLLBACK')], max_length=32),
        ),
        migrations.AlterField(
            model_name='reseedledger',
            name='stage',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('STATEMENT_WRITTEN', 'STATEMENT_WRITTEN'), ('SIGNATURE_WRITTEN', 'SIGNATURE_WRITTEN'), ('CONTRACT_SET', 'CONTRACT_SET'), ('COMPLETE', 'COMPLETE'), ('FAILED', 'FAILED')], default='PENDING', max_length=24),
        ),
    ]
