# Generated by Django 5.2.16 on 2026-08-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0049_reseed_contract_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencesolution',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='referencesolution',
            name='origin',
            field=models.CharField(choices=[('human', 'Written by a person'), ('llm', 'Generated by a language model'), ('trusted_source', 'Taken from a trusted external source'), ('unrecorded', 'Predates provenance recording')], default='unrecorded', max_length=20),
        ),
        migrations.AddField(
            model_name='referencesolution',
            name='prompt_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='referencesolution',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='referencesolution',
            name='specification_digest',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='referencesolution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('origin', 'llm'), _negated=True), models.Q(models.Q(('provider', ''), _negated=True), models.Q(('prompt_version', ''), _negated=True)), _connector='OR'), name='reference_llm_origin_requires_attribution'),
        ),
    ]
