# Generated by Django 5.2.16 on 2026-09-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0051_trust_demotion_action_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationlog',
            name='served_adaptive_eligible',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
