# Generated by Django 5.2.17 on 2026-09-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0053_question_verified_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationaction',
            name='action_class',
            field=models.CharField(choices=[('CONTRACT_REPAIR', 'CONTRACT_REPAIR'), ('STATEMENT_REPAIR', 'STATEMENT_REPAIR'), ('BOILERPLATE_REPAIR', 'BOILERPLATE_REPAIR'), ('HIDDEN_TEST_REPAIR', 'HIDDEN_TEST_REPAIR'), ('EXPECTED_OUTPUT_REPAIR', 'EXPECTED_OUTPUT_REPAIR'), ('INPUT_REPAIR', 'INPUT_REPAIR'), ('SUITE_EXPANSION', 'SUITE_EXPANSION'), ('STATEMENT_GENERATION', 'STATEMENT_GENERATION'), ('SIGNATURE_DECLARATION', 'SIGNATURE_DECLARATION'), ('CONTRACT_DECLARATION', 'CONTRACT_DECLARATION'), ('CONTRACT_MIGRATION', 'CONTRACT_MIGRATION'), ('TRUST_DEMOTION', 'TRUST_DEMOTION'), ('STATUS_TRANSITION', 'STATUS_TRANSITION'), ('MANUAL_REVIEW', 'MANUAL_REVIEW'), ('COMPLETE_REBUILD', 'COMPLETE_REBUILD'), ('ROLLBACK', 'ROLLBACK')], max_length=32),
        ),
    ]
