# Generated by Django 5.2.16 on 2026-08-02 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=64, unique=True)),
                ('last_run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('succeeded', models.BooleanField(default=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['task'],
            },
        ),
    ]
